spring:
  datasource:
    url: jdbc:postgresql://${connection:localhost}:5432/application-dev
    username: dbuser
    password: 12345
    thymeleaf:
      cache: false
    jpa:
      show-sql: true

liquibase:
  drop-first: true